name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        uses: https://github.com/rithesh1307/hello-world-javascript-action@v1.1
        with:
          who-to-greet: John
    